### ISSUE TITLE
Content rendering messed up on Apple feeds

### ISSUE THREAD

**Issue by mttjj** [feedbin/support#141]
I'm subscribed to some feeds from Apple - new items in the iTunes store and new items in the Mac App Store. Here's the feed for the MAS: http://itunes.apple.com/us/rss/topmacapps/limit=25/xml

Anyway, the formatting in those feeds is messed up. Here's an example of what I'm talking about. I've since unsubscribed to the iTunes music feed but I remember having this issue with that feed as well. Not a huge deal but would be nice to be fixed.

![](http://d.pr/i/yJ4f+)

**Comment by peterc** [comment]
Stumbled across this as we are finding the RSS feeds for our email newsletters have borders everywhere in Feedbin :) Tables are used because it just converts the formatting from the email (where table is a necessary evil, alas). We might look at other ways to deal with the problem, but just wanted to highlight another instance why tables might still be used.

**Comment by benubois** [comment]
@peterc,

Yes, Ruby Weekly is probably the one remaining place I still see tables as layout once-per-week :) 

![screen shot 2017-04-04 at 9 03 24 am](https://cloud.githubusercontent.com/assets/133809/24666863/5b6294d6-1916-11e7-8f70-8b2bc7be5218.png)

I'm sure there are countless more newsletters taking the HTML from the email and putting it in the RSS feed too.

I had an idea for how to address this though. A very simple test. If `<table>` is the first tag of the content, then that could be a good indication that tables are being used for layout. Then Feedbin could style them differently.

Do all of your email templates start with `<table>`?

**Comment by peterc** [comment]
Haha, a handy coincidence :) So I checked and.. not exactly. We are transitioning systems. Our old ones do start with tables, our new ones start with a tracking pixel IMG tag. But.. I could get that moved to the end instead and in theory have <table> at the start so it seems like a reasonable way forward that shouldn't catch anything it shouldn't.

**Comment by benubois** [comment]
OK this is live. It works when the content starts with `<table>`.

I think semantic markup + tables could be a good fit here. That way Feedbin could benefit from the markup and CSS could be used to reset HTML elements to look consistent in email clients.

![screen shot 2017-04-06 at 2 18 37 pm](https://cloud.githubusercontent.com/assets/133809/24776155/85eea20c-1ad4-11e7-8eb6-8767cd9a24ea.png)

**Comment by peterc** [comment]
We're going to continue to improve it but this looks like a fantastic start, thanks! :)
