### ISSUE TITLE
Duplicate entries showing

### ISSUE THREAD

**Issue by johnbillion** [feedbin/support#431]
[This feed from wordpress.org](http://wordpress.org/plugins/rss/browse/new/) has started showing duplicate entries since the site changed from being served over HTTP to being served over HTTPS. One entry contains an HTTP link and the other contains an HTTPS link.

When you view the raw feed you'll see that it does not contain duplicate entries.

Screenshot:

![screen shot 2014-03-04 at 20 03 14](https://f.cloud.github.com/assets/208434/2325655/4f018366-a3d8-11e3-87d7-02f36aed7cc3.png)

**Comment by benubois** [comment]
Looks like the issue has reappeared.

**Comment by johnbillion** [comment]
Specific to WordPress.org/com feeds?

**Comment by benubois** [comment]
[This feed](http://wordpress.org/plugins/rss/browse/new/) on wordpress.org as well as `*.wordpress.com` feeds.

An example from Feedbin's database:

```
irb(main):005:0> e = Entry.find([1111098483,1111095675])
irb(main):006:0> e.first.entry_id
=> "https://flipchartfairytales.wordpress.com/?p=9817"
irb(main):007:0> e.last.entry_id
=> "http://flipchartfairytales.wordpress.com/?p=9817"
```

**Comment by johnbillion** [comment]
Reported to WordPress' meta bug tracker: https://meta.trac.wordpress.org/ticket/1652

**Comment by benubois** [comment]
I've given up hope that WordPress will address this issue so I've made some changes that I think will solve the problem. Feedbin will now proactively block an article where the only difference in guid is http -> https or vice versa. 

Please let me know if you see any duplicates show up in wordpress.com feeds published later than now.
