### ISSUE TITLE
Unsubscribe from the feed to which the current entry belongs

### ISSUE THREAD

**Issue by rybesh** [feedbin/support#462]
I often find myself coming upon a new entry in my unread entries list, and realizing that I would like to unsubscribe from the feed (often this is an "alert" RSS feed that is no longer relevant). But unsubscribing from feeds is currently so cumbersome that I usually just skip past it. It's now at the point where I am spending a lot of time skipping past stuff I no longer want to be subscribed to. It would be _really_ nice if there were an easy way to unsubscribe from the feed to which the current entry belongs.

**Comment by sepehr** [comment]
I'm dying for this!

**Comment by rybesh** [comment]
This got added a while back, thanks!
