### ISSUE TITLE
Spiegel Online Feed wasn't updated in Feedbin for 3 Days

### ISSUE THREAD

**Issue by PascalTurbo** [feedbin/support#495]
Hi There,

I wondered why I didn't receive any news from www.spiegel.de for about 3 Days. I thought they had problems with there feed but the feeds seems to work: http://www.spiegel.de/schlagzeilen/index.rss

I tried removing and re adding the feed but feedbin only shows old feeds (The last one from December 29th)

I home you will fix this soon.

Bests Pascal

**Comment by Erdnuckl** [comment]
Hi,

I have the same problem. This seems to be a problem with feedbin, because the dynamic bookmarks in Firefox show current entries.

Best regards,
Erdnuckl

**Comment by benubois** [comment]
Hi @PascalTurbo,

Thanks for reporting this. The feed should be updating now.

Sorry for the trouble!
