### ISSUE TITLE
Page Up & Page Down don't work on Linux Chrome

### ISSUE THREAD

**Issue by btakita** [feedbin/support#496]
I'm attempting to Page Up & Page Down on Linux Chrome. No work.

**Comment by benubois** [comment]
Hi @btakita,

Thanks for reporting this. What distro is this happening on?

Also would you mind letting me know what keycodes are being triggered when you press Page Up and Page Down? [This page](http://www.ryancooper.com/resources/keycode.asp) can give you those.

Feedbin uses the [Mousestrap](http://craig.is/killing/mice) library for capturing keyboard events and it looks like it's [expecting keycodes 33 and 34](https://github.com/ccampbell/mousetrap/blob/master/mousetrap.js#L44-L45).

**Comment by btakita** [comment]
I was expecting Page Up & Page Down to move the select cursor in the left
(feeds) & center (articles) panes.

Page Up & Page Down works in the right (aricle) pane.

On Sun, Jan 4, 2015 at 11:47 PM, Ben Ubois <notifications@github.com> wrote:

> Hi @btakita <https://github.com/btakita>,
>
> Thanks for reporting this. What distro is this happening on?
>
> Also would you mind letting me know what keycodes are being triggered when
> you press Page Up and Page Down? This page
> <http://www.ryancooper.com/resources/keycode.asp> can give you those.
>
> Feedbin uses the Mousestrap <http://craig.is/killing/mice> library for
> capturing keyboard events and it looks like it's expecting keycodes 33
> and 34
> <https://github.com/ccampbell/mousetrap/blob/master/mousetrap.js#L44-L45>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/feedbin/support/issues/496#issuecomment-68668107>.
>



-- 
Brian Takita
briantakita.com
about.me/brian_takita

**Comment by benubois** [comment]
Ah ok, the arrow keys do that.

**Comment by btakita** [comment]
The arrow keys are ok, but the issues I'm having with the arrow keys are:

* all articles are marked as read when quickly navigating down the articles
* navigating through the articles is slow
* it's not as easy to scan the articles page-by-page with arrow key as it
is with page up & page down

Thanks!

On Mon, Jan 5, 2015 at 2:40 AM, Ben Ubois <notifications@github.com> wrote:

> Ah ok, the arrow keys do that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/feedbin/support/issues/496#issuecomment-68676642>.
>



-- 
Brian Takita
briantakita.com
about.me/brian_takita
