### ISSUE TITLE
Email newsletter subscriptions → Feedbin

### ISSUE THREAD

**Issue by carlbennettnz** [feedbin/support#497]
It would be nice to be able to use a special Feedbin email address to subscribe to email newsletters and then receive those newsletters alongside normal RSS feeds. I imagine parsing the emails would be quite difficult, but I thought I might as well put the idea out there.

**Comment by benubois** [comment]
Hi @carlbennettnz,

Thanks for the suggestion. I like this idea!

I'll definitely look into this.

**Comment by Zegnat** [comment]
@carlbennettnz, ’til such a feature makes it into Feedbin you could look at several disposable email providers. Those often offer an RSS feed for their inboxes. (I was going to recommend Mailinator for this, but it seems they have switched to offering an API instead.)

**Comment by carlbennettnz** [comment]
@Zegnat Hmm, sounds like that could work. I'll look into it, thanks.

**Comment by benubois** [comment]
This is now [supported natively](https://feedbin.com/blog/2016/02/03/subscribe-to-email-newsletters-in-feedbin/).

**Comment by carlbennettnz** [comment]
Awesome, thanks so much!

**Comment by kkga** [comment]
This is so great!
How does confirming a subscription work? I don't get anything in Feedbin after subscribing.
