### ISSUE TITLE
Feed filled with #

### ISSUE THREAD

**Issue by alexbilbie** [feedbin/support#498]
I subscribe to this feed - http://phpquickfix.me/feed

For the last few days my subscription in Feedbin has contained mostly feed items with titles and descriptions that just contain `#`.

![screen shot 2015-01-11 at 19 44 17](https://cloud.githubusercontent.com/assets/77991/5696466/5eac3138-99ca-11e4-9315-91377bb485f8.png)

There doesn't appear to be anything wrong with the feed from what I can see:

`curl http://phpquickfix.me/feed | head -n 100`

**Comment by benubois** [comment]
Hi @alexbilbie,

I believe this is an issue with the feed. For a while it would post empty entries which you are seeing here.

I also took a look at their twitter account which cross-posts the same content and you can see some [odd looking tweets](https://twitter.com/phpquickfix/status/554530738490462209) as well.

As of this morning I see some legitimate entries so maybe the problem has cleared up?

**Comment by alexbilbie** [comment]
Thanks @benubois
