### ISSUE TITLE
"Mark Above/Below as Read" doesn't work in the Updated tab

### ISSUE THREAD

**Issue by t0mm1** [feedbin/support#499]
As stated in the title, the option to "Mark Above as Read" or "Mark Below as Read" doesn't set the status to "read" for the articles in question.
The CSS is changed, though, so they appear as read, but the number of unread articles doesn't decrease, as well as after reloading the page or reselecting the "Updated" tab, the articles appear again as unread.

**Comment by benubois** [comment]
Thanks for reporting this @t0mm1. Should be fixed now.

**Comment by t0mm1** [comment]
Works fine so far. Thanks for the fast fix!
