### ISSUE TITLE
Duplicate Items in The Dissolve feeds

### ISSUE THREAD

**Issue by edcorcoran** [feedbin/support#500]
All the feeds that I subscribe to from The Dissolve have had duplicate items for the past few months. Every item in these feeds shows up exactly twice. The second version of the item doesn't show up immediately, but generally shows up between 24 and 48 hours later.

In the screenshot below, you can see that the most recent news items don't have duplicates, but slightly older ones all have duplicates.

![dissolve dupes](https://cloud.githubusercontent.com/assets/31132/5894313/701cfba6-a4c8-11e4-99f8-376780617755.png)

Here are the feeds:
http://thedissolve.com/feeds/news/
http://thedissolve.com/feeds/reviews/
http://thedissolve.com/feeds/features/
And here's the list of all their feeds: https://thedissolve.com/rss/

**Comment by benubois** [comment]
Hi @edcorcoran,

Thanks for reporting this.

I took a look at the feed and I think I see what is going on. 

RSS feeds usually have an ID that is supposed to uniquely identify articles so readers like Feedbin can tell what is new.

However for this feed it looks like the ID changes periodically which indicates to Feedbin that it is a new article.

For example this article shows up three times in Feedbin with two different IDs.

```xml
<guid>http://thedissolve.com/news/4544-two-decades-in-the-making-martin-scorseses-silence/</guid>
<guid>https://thedissolve.com/news/4544-two-decades-in-the-making-martin-scorseses-silence/</guid>
```
Unfortunately I don’t have a solution for how to deal with an issue like this. I sent an email to their support email address and hopefully they’ll be able to fix this on their end.

Thanks,

Ben

**Comment by edcorcoran** [comment]
They seem to have resolved the issue, as I haven't seen a dupe today.
