### ISSUE TITLE
Shift+V no longer opening in background

### ISSUE THREAD

**Issue by zacharydanger** [feedbin/support#501]
In Chrome 41.0.2272.43 beta (64-bit) on OS X, the "shift+v" and "v" keyboard shortcuts are behaving identically.

**Comment by benubois** [comment]
Hi @zacharydanger,

Yeah, that is a bummer.

I think Google is [intentionally changing the behavior of generated events](https://code.google.com/p/chromium/issues/detail?id=431335) to prevent abuse. However this hurts legitimate uses.

I've [reported the issue](https://code.google.com/p/chromium/issues/detail?id=456910) so we'll see what they say.

**Comment by zacharydanger** [comment]
Ah. Good to know. Thanks.

**Comment by braindeath** [comment]
I too have this issue :(
Chrome 41.0.2272.76 (64-bit) @ Yosemite 10.10.2

**Comment by Zegnat** [comment]
I think this should be labeled as ‘Upstream’, and possibly closed. Chromium has [marked this as WontFix](https://code.google.com/p/chromium/issues/detail?id=456910#c3), so it looks like this feature will never be heading back to Feedbag (or any other browser-based RSS reader) :disappointed:

**Comment by braindeath** [comment]
Not acceptable. This IS a massive PITA since it changes the way I (and other) used to use Feedbin.

**Comment by Zegnat** [comment]
> Not acceptable.

What is not acceptable?

Chromium made a change to stop websites from opening tabs in the background as it was used for advertising and other such things. In this they aligned their policy with other browsers, this trick has never worked in non-WebKit browsers. Of course you are free to, at any point, open a ticket for your favourite browser and ask them to allow this again.

Feedbin’s JavaScript code is completely correct though, and there is no bug in the code. It is completely up to “upstream” browser implementations.

**Comment by benubois** [comment]
Sounds like this is gone from Chrome for good based on the [responses to the issue](https://code.google.com/p/chromium/issues/detail?id=431335) I filed.

I've created a [Chrome extension](https://chrome.google.com/webstore/detail/feedbin-link-opener/naflkhnfmneiigdcphekaemdmeajiand) to restore this functionality.

[More about this on the blog](http://blog.feedbin.com/2015/03/09/link-opener-for-chrome/).
