### ISSUE TITLE
Article age shown instead of proper date

### ISSUE THREAD

**Issue by abspann** [feedbin/support#504]
This is just a minor issue, I know, but one of the last updates changed the article date in the middle column from the proper date to the age of the article. While that's no problem for newer articles ("15min", "2h", "3d") it bugs me that the dates of older articles become very blurry ("1 month", "2 months").

I have the habit of keeping some stuff unread for several weeks, so I'd really appreciate if the "old date view" would come back (maybe as an option in the settings?)

Thanks and keep up the good work!

**Comment by nbousfield** [comment]
I'm not sure when this change happened, but I would really like the old format back, too.

**Comment by benubois** [comment]
Ok, should be back to the old format.

Thanks!
