### ISSUE TITLE
AppleWorld.Today Feed Not Refreshed

### ISSUE THREAD

**Issue by kolpanic** [feedbin/support#506]
The RSS feed for [AppleWorld.Today](http://www.appleworld.today) hasn't been updated on Feedbin since March 18. However, the site contains articles since then, and the curl'ed feed has items for them.

I've tried deleting and re-adding the feed, without success, both in Reeder.app on OS X and the Feedbin web app.

Here are the `feed.xml` and `headers.txt` as a Gist:
https://gist.github.com/kolpanic/095b65e36e566cb90a27

**Comment by benubois** [comment]
Hi @kolpanic,

Sorry for the trouble.

Squarespace, which hosts AppleWorld.Today, is currently blocking Feedbin's feed refreshing servers from downloading any sites in their network. 

The issue has been reported to Squarespace and the latest I've heard is that the issue has been handed off to Squarespace engineering to fix it.

I'll update this issue when access is restored.

Thanks!

**Comment by kolpanic** [comment]
@benubois Thanks for the quick update!

**Comment by benubois** [comment]
Looks like the Squarespace issue is resolved so this feed should be updating again.

**Comment by kolpanic** [comment]
:+1:
