### ISSUE TITLE
Retail Comic RSS feed missing entries

### ISSUE THREAD

**Issue by Gidgidonihah** [feedbin/support#507]
In my history I am missing the entries from April 9, 10, 11 and 13. 

See https://gist.github.com/Gidgidonihah/ee3dd527bac7feccacc4

**Comment by benubois** [comment]
Hi @Gidgidonihah,

Looks like the publisher is re-using [`guids`](http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fretailcomic.com%2Fcomics%2Ffeed%2F) which indicates to Feedbin that these are all the same entries.

This problem must be fixed by retailcomic.com.

Thanks!

**Comment by Gidgidonihah** [comment]
Ok, great. I'll get in touch with them. Thanks!
