### ISSUE TITLE
Evo.co.uk feeds not updating

### ISSUE THREAD

**Issue by JoSpalding** [feedbin/support#514]
Please, take a look at these 2 feeds that are not updating in Feedbin:
- http://www.evo.co.uk/reviews/feed
- http://www.evo.co.uk/news/feed

However, this seems to be ok:
- http://www.evo.co.uk/feeds/all

**Comment by benubois** [comment]
Hi @JoSpalding,

I took a look at these feeds and I don't see anything wrong with them. 

Feedbin does not refresh feeds that nobody is subscribed to so I think if you subscribe to them they will resume updating. 

Thanks!

**Comment by JoSpalding** [comment]
Hi @benubois,
As your suggestion, I have just subscribed to the feeds and after awhile the magic happened! :+1: 

Just want to let you know that I think Feedbin is great and has an amazing price! Also, I really enjoyed to read your blog post about you infrastructure.

Congratulations and thank you for the support!
