### ISSUE TITLE
Feed not found

### ISSUE THREAD

**Issue by poindexter6** [feedbin/support#531]
The following feeds work fine in other readers but return the "Feed Not Found" error with Feedbin:

http://www.flyertalk.com/forum/external.php?type=rss2&forumids=178
http://www.flyertalk.com/forum/external.php?type=RSS2&forumids=411
http://www.flyertalk.com/forum/external.php?type=rss2&forumids=730

**Comment by benubois** [comment]
Hi, these feeds have encoding issues and cannot be parsed by Feedbin: https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.flyertalk.com%2Fforum%2Fexternal.php%3Ftype%3Drss2%26forumids%3D178
