### ISSUE TITLE
Misleading billing receipts

### ISSUE THREAD

**Issue by banrobert** [feedbin/support#532]
The Item field on the receipts always shows your current subscription plan (i.e. Monthly Subscription or Yearly Subscription), even if you changed your plan since the receipt was created. Because of this, if you change from a Monthly Subscription to a Yearly Subscription, all your previous receipts will show the wrong Item on them (Yearly Subscription instead of Monthly Subscription). It is also true the other way around.

**Comment by benubois** [comment]
Thanks for pointing this out! The receipts have been updated to accurately reflect the plan you had when the charge was processed.
