### ISSUE TITLE
Gamespot RSS Feeds No Longer Update in Feedbin

### ISSUE THREAD

**Issue by dhill171** [feedbin/support#536]
Gamespot news RSS feeds stopped updating in Feedbin on March 17th. Viewing the feed in other readers such as Apple News and Reeder (local) show the feed updating. I have created a gist (https://gist.github.com/anonymous/117ac2fc1548dc0096b9) headers.txt and feed.xml files.

**Comment by benubois** [comment]
Hi @dhill171,

Looks like this feed is working at the moment. I looked at the reviews feed and did see an issue though. Gamespot is doing some sort of check to see if the website is being loaded in a browser vs. a script, and blocking access to scripts downloading their content. I believe this to be an oversight on their part, in the case of RSS feeds, and have contacted them at support@gamespot.com.

Thanks!

**Comment by dhill171** [comment]
The feed appears to be working again. Gamespot found and fixed the error this morning. 

Thank you very much.
