### ISSUE TITLE
#FeatureRequest As a desktop user, when I search the "Feeds" section, I want to find/query domains/URLs so I can prune feeds

### ISSUE THREAD

**Issue by ldexterldesign** [feedbin/support#543]
Hey,

Thanks for application

http://quick.as/4kdWhAxwA - screencast

If you agree reply +1 or vote this up

I'll follow this up again in the near future and base my decision to keep using https://feedbin.com/ on whether it's been fixed

Lastly, please let me know if there's a more suitable place to leave issues?

Look forward to your reply

Kind thanks

**Comment by ldexterldesign** [comment]
BUMP

**Comment by benubois** [comment]
Hi @ldexterldesign,

Thanks for the suggestion, this has been added.

Also there is no need to "BUMP" your own issues as that generates extra email noise 😄

**Comment by ldexterldesign** [comment]
Hey,

Apologies, yep, that was a mistake, so I deleted the "BUMP"

Once labels have been added to the issue that's acknowledgment enough for me

Good luck with the feature and hope to see it soon

Kind regards

**Comment by ldexterldesign** [comment]
Ahh, I see this has already been implemented - thanks!

I understand it may be against the app's minimal paradigm. However it would still be useful to see the domain/URL visible in the UI; without the progressive disclosure

Example:

<img width="1440" alt="screen shot 2016-07-19 at 10 23 58" src="https://cloud.githubusercontent.com/assets/1715809/16943277/38d206a0-4d9b-11e6-948a-817b62920c5f.png">

Hope to hear back

Kind thanks

**Comment by ldexterldesign** [comment]
Has this feature reverted?

Today I'm having issues querying URLs http://quick.as/lQ35C2Dpy ?

Look forward to your reply

Kind thanks

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by nbousfield** [comment]
Can you please stop bumping all of your threads?

**Comment by ldexterldesign** [comment]
@nbousfield hey, are you support?

If not, and you have nothing constructive to offer, can you please stop creating more noise

Kind thanks

**Comment by nbousfield** [comment]
I'm not support. I don't think this will be added though, because very few
people will use it.

Also, bumping creates more noise, not my post.

**Comment by ldexterldesign** [comment]
@nbousfield you're wrong; users should be able to search by feed title/name and URL - these feed criteria often wildly different

Example (happens to be the first in my feed list):



NB @benubois added this enhancement ( https://github.com/feedbin/support/issues/543#issuecomment-233452879 ), but it's not working, hence me following this up

Regards

**Comment by benubois** [comment]
@ldexterldesign,

Please be respectful on here. I have already asked you  to not BUMP your own issues. This is a feature request, not support. Feedbin is developed according to my own priorities for better or worse. 

Anybody who watches this repository gets notifications when you BUMP so people like @nbousfield, who does try to help people on here, has to see the extra notifications. 

Thanks!

**Comment by ldexterldesign** [comment]
Hey @benubois, 

Thanks for reply

Apologies for bringing up my post (BUMP) *again*

I do it as a matter of principle, usually following up three times. If nothing is resolved after the third strike I blackmark it and let it go (not good, since I'm a paying customer) - this helps me manage my priorities (like finding a new feed reader 😊)

I try to be considerate about the timeframes I use (I service clients too), as you'll see; often leaving weeks or months between following up issues

--

You mention this is not for support (semantics at this point IMO), yet the repository's README states:

```
Feedbin Support

Welcome to Feedbin support. You can

Email support support@feedbin.me
Open a new support request
Visit Feedbin Help
```

I would be happy to draft you a new email on this issue if that's what it will take to get a reply to my question/s, but I sent you an email on 2016-08-18 (15 days ago), on a separate issue, and still haven't received a reply..?

--

I have 4 other open issues (mixture of feature requests / support), three of which are over a month old now, with no responses:

2016-07-14 https://github.com/feedbin/support/issues/544
2016-07-22 https://github.com/feedbin/support/issues/545
2016-07-29 https://github.com/feedbin/support/issues/546
2016-08-12 https://github.com/feedbin/support/issues/548

I've come to value your app' in the three months since I purchased a subscription (it's one of the best I could find in a sea of languishing competition https://twitter.com/ldexterldesign/status/712366618324672514 ), but I'm quickly losing patience with the lack of communication/support and will be looking elsewhere if I don't see an improvement

Lastly, can you let me know what's happening with this feature request - it's status is *closed*, so, unless I hear back shortly, I assume it won't get implmented?

Look forward to your reply

Yours faithfully,
