### ISSUE TITLE
Duplicate entries appear for each post on a particular wordpress.com feed

### ISSUE THREAD

**Issue by wjt** [feedbin/support#549]
I subscribe to [this feed](https://stronglang.wordpress.com/feed/) in Feedbin. The blog has roughly one post every fortnight. For some reason, Feedbin duplicates every update:

![screenshot from 2016-09-12 07-16-13](https://cloud.githubusercontent.com/assets/86760/18426346/dc57a58a-78b8-11e6-8df4-7d904e59fefd.png)

The identifiers for these two posts in my account are `https://feedbin.com/entries/1243542352` and `https://feedbin.com/entries/1243544254`. This duplication happens reliably for every post. I don't see this issue on any other blog. Looking at the feed right now, the posts do not seem to be duplicated. This suggests that either each post is published, and then republished with a new identifier in the feed shortly afterwards; or a bug in Feedbin.

**Comment by cfranke** [comment]
Same here with https://whyistheinternetbroken.wordpress.com/feed

**Comment by plel** [comment]
Also with https://gramseleblog.wordpress.com/

It seems, as if only the quotations are different. One entry is displayed with „ and the other with “. The feed only contains the lower quotations.

**Comment by benubois** [comment]
Yes, unfortunately this is an issue with all *.wordpress.com feeds. They had fixed this on their side at one point but then it came back. More in #431.
