### ISSUE TITLE
Missing Articles on fivethiryeight.com 

### ISSUE THREAD

**Issue by benubois** [feedbin/support#555]
fivethiryeight.com is using `dc:identifier` for author URLs. I think this is a mistake, because as I understand it, `dc:identifier` should [uniquely identify an entry](https://goo.gl/ZzBA29). I sent the following to contact@fivethirtyeight.com:

> Hello,
> 
> This is a support request for the web development team.
> 
> I work on an RSS reader called Feedbin, https://feedbin.com.
> 
> Recently several customers have reported an issue with missing updates from fivethirtyeight.com RSS feeds.
> 
> I think the issue has to do with the recent addition of the `dc:identifier` element to fivethirtyeight.com’s feeds. 
> 
> fivethirtyeight.com is using this element as a link to the author bio, however I think is incorrect and is causing an issue.
> 
> According to "RSS and Atom: Understanding and Implementing Content Feeds and Syndication” https://goo.gl/ZzBA29 the value for dc:identifier is supposed to be a unique identifier similar to a guid. A guid uniquely identifies RSS entries so repeating the same guid makes articles that share the same dc:identifier look identical.
> 
> It would be great if the feeds could be updated to not use `dc:identifier` in this way.
> 
> Thanks!
> 
> Ben Ubois

**Comment by nbousfield** [comment]
have there been any updates on this? I'm assuming not because I'm still missing many FiveThirtyEight articles, so I sent them an email as well.

**Comment by nbousfield** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/nbousfield_">@nbousfield_</a> Fix is live now.</p>&mdash; Paul Schreiber (@paulschreiber) <a href="https://twitter.com/paulschreiber/status/826199239957028865">January 30, 2017</a></blockquote>

**Comment by nbousfield** [comment]
close #555

**Comment by benubois** [comment]
Thanks @nbousfield!
