### ISSUE TITLE
Article action doesn't work

### ISSUE THREAD

**Issue by rrrrfischer** [feedbin/support#556]
I defined a article action for the term "[Werbung] " (which simply flags payed articles) to mark every matching article in every feed as read. Unfortunately it doesn't work at all. Is it a bug or did I something wrong?

Please see attached screenshot of the action definiton.
![shot_161115_112846](https://cloud.githubusercontent.com/assets/23475184/20302248/cb38970a-ab26-11e6-9d03-a3a5c114db0c.png)

**Comment by benubois** [comment]
Hi @rrrrfischer,

I think the issue is with the brackets `[]` If you just search for `Werbung` I think it should work.

Thanks!

**Comment by benubois** [comment]
`title:"Werbung"` would be better if this always appears in the title.

**Comment by rrrrfischer** [comment]
Hi Ben, unfortunatelly the word "Werbung" (means advertising) is also part of regular subjects for non sponsored articles, which then also get marked read. Depending on the feed you read, the word occurs very often in regular articles. Especially in Germany its very common that sponsored articles are marked with "[Werbung]". Is there any chance, you can provide a "fix" to make those rules working?

I would be happy :)
