### ISSUE TITLE
Readability API is no longer available

### ISSUE THREAD

**Issue by sepehr** [feedbin/support#557]
As you might already know, [Readability is no longer available](https://www.readability.com). Neither the bookmarking service nor the Parser API.  

This was a feature I used to use every day to read my feeds on Feedbin. But now, it's gone. 

Do you have any plans to replace it with another service soon?

**Comment by Zegnat** [comment]
This has been discussed [on the blog](https://feedbin.com/blog/2016/12/06/regarding-readability/):

> Readability offered two services both named Readability.
> 
> 1. A read-it-later/Instapaper type of service. Feedbin offered an integration to let you easily add links to your Readability account. This has been removed from Feedbin.
> 2. A parser API. Feedbin used this service to provide the full content of partial-content feeds. This functionality will continue to exist in Feedbin, but powered by Diffbot.

I hope this answers your question.

**Comment by sepehr** [comment]
Haven't seen that. Thanks for pointing me out.
