### ISSUE TITLE
Weird Unwanted Newsletter

### ISSUE THREAD

**Issue by sepehr** [feedbin/support#560]
I just got an unwanted newsletter in my feed. I'm quite sure that I haven't subscribed to it. More weirdly it does not have a valid subscription URL. 

Here's a few screenshots for you, in case you want to investigate it. 

![screen shot 2017-01-09 at 1 31 32 pm](https://cloud.githubusercontent.com/assets/23576/21762875/47e6cd84-d670-11e6-8df2-a00435e35fe1.png)
![screen shot 2017-01-09 at 1 31 43 pm](https://cloud.githubusercontent.com/assets/23576/21762876/47ea0e40-d670-11e6-9a32-3a2bdf2f2216.png)

**Comment by benubois** [comment]
Hi @sepehr,

That is strange, but it doesn't look like an issue with Feedbin. This email was sent to your unique Feedbin newsletter address. I'd be happy to regenerate the address for you. That would mean you would have to resubscribe/update your email address on any legitimate newsletter.

Have you subscribed to any other newsletters? If so I'm thinking one of them may have sold their list to spammers.

Thanks!

**Comment by sepehr** [comment]
Hey Ben,

Yes, I subscribed to other legitimate*-looking* newsletters. But seems like someone's out of cash!

No, thanks, I'm fine with the current address for now. Let's see how bad is the situation. I'll reopen this in case I needed a new address.

Thanks for your support.
