### ISSUE TITLE
Feed entry summary removes double letters

### ISSUE THREAD

**Issue by liggitt** [feedbin/support#562]
As you can see in the attached screenshot, my username, the word "pull", and the word "commented" all ommitted doubled letters.

The text is correct when I view it in the main screen

![screen shot 2017-01-14 at 9 05 46 pm](https://cloud.githubusercontent.com/assets/980082/21959839/e27193d6-daa1-11e6-8229-b4e1238a8b5f.png)

**Comment by benubois** [comment]
Thanks! This is fixed now.
