### ISSUE TITLE
No images when in "attempt to load full content" mode

### ISSUE THREAD

**Issue by radoslawcz** [feedbin/support#572]
Many different feeds which show snippest when I click to  "attempt to load full content" the feed does load full but with no images. Instead of an image there is an icon that shows missing item but when clicked it loads the image. Certainly a bug which discourages of using feedbin. Should be corrected ASAP. 

I can give example feeds if needed.

**Comment by benubois** [comment]
Yes please always include feed urls and screenshots when possible. 

Thanks!

**Comment by radoslawcz** [comment]
feed: http://discoposse.com/feed/
image: http://pasteboard.co/NZQ2ggVVW.png

**Comment by radoslawcz** [comment]
feed: https://sekurak.pl/feed/
image: http://pasteboard.co/NZZLthhgs.png

**Comment by radoslawcz** [comment]
feed: http://www.drunkendata.com/?feed=rss2
image: http://pasteboard.co/O03Q1qXT6.png

**Comment by radoslawcz** [comment]
feed: https://www.nextplatform.com/feed/
image: http://pasteboard.co/O07YDfDFy.png

**Comment by radoslawcz** [comment]
feed: http://feeds.feedburner.com/tabletmaniak
image: http://pasteboard.co/O0grp4GPw.png

**Comment by benubois** [comment]
Thanks for the examples!

Feedbin uses [Mercury Parser](https://mercury.postlight.com/web-parser/) to power this feature. Unfortunately Mercury Parser mangles images with the `srcset` attribute.

I actually reported this issue to Mercury in early January and never heard back. 

Since it's been a long time with no movement on Mercury's side, I'll look into a work-around on Feedbin's side.

This is the report I sent to Mercury on 2017/01/03:

> Hello!
> 
> I'm evaluating the Web Parser API and wanted to report an issue.
> 
> Take this page as an example: http://foodinjars.com/2017/01/cookbooks-perfect-blend/
> 
> The following HTML gets transformed, which breaks the image.
> 
> Original:
> `<img class="alignnone size-large wp-image-10977" src="http://foodinjars.com/arugulapesto/wp-content/uploads/2017/01/Potato-Leek-Soup-The-Perfect-Blend.jpg" alt="" width="640" height="424" srcset="http://foodinjars.com/arugulapesto/wp-content/uploads/2017/01/Potato-Leek-Soup-The-Perfect-Blend.jpg 640w, http://foodinjars.com/arugulapesto/wp-content/uploads/2017/01/Potato-Leek-Soup-The-Perfect-Blend-300x199.jpg 300w" sizes="(max-width: 640px) 100vw, 640px" />`
> 
> Parser result:
> `<img src="http://foodinjars.com/arugulapesto/wp-content/uploads/2017/01/Potato-Leek-Soup-The-Perfect-Blend.jpg%20640w,%20http://foodinjars.com/arugulapesto/wp-content/uploads/2017/01/Potato-Leek-Soup-The-Perfect-Blend-300x199.jpg%20300w" srcset="http://foodinjars.com/arugulapesto/wp-content/uploads/2017/01/Potato-Leek-Soup-The-Perfect-Blend.jpg 640w, http://foodinjars.com/arugulapesto/wp-content/uploads/2017/01/Potato-Leek-Soup-The-Perfect-Blend-300x199.jpg 300w" class="alignnone size-large wp-image-10977" alt="">`
> 
> It looks like the parser is replacing the `src` attribute with a collapsed copy of `srcset` and also dropping the `sizes` attribute.
> 
> Ideally Web Parser would pass the HTML through as is.
> 
> Thanks!
> 
> Ben

**Comment by OJFord** [comment]
I was about to open an issue, but I believe it might be very related to this - it seems that everything up to the last occurrence of certain media elements (videos, embedded tweets sometimes) is stripped, leaving just a fragment of the article.

I notice it most frequently with *[The Telegraph](www.telegraph.co.uk/rss)* - so for example [this article](http://www.telegraph.co.uk/news/2017/03/28/daily-mail-tells-bbc-get-life-sexist-legs-it-story/) begins on Feedbin as:

![screen shot 2017-03-28 at 16 29 29](https://cloud.githubusercontent.com/assets/3946014/24413579/c35a1a16-13d3-11e7-9a25-d743aaeec3d2.png)

which is actually the closing paragraph on the website; immediately follows a `blockquote`.

**Comment by radoslawcz** [comment]
@benubois Thank you for your response. Looking forward to the fix :)

**Comment by benubois** [comment]
I think this should be fixed now. 

@OJFord, that sounds unrelated and should be a separate issue. However there's not much I can do about results from Mercury. This image thing had a clear pattern so it was able to be addressed.

If you are interested in trying to improve the results, I would recommend [emailing Mercury support](mailto:mercury@postlight.com) with issues that you find. Thanks!

**Comment by OJFord** [comment]
Thanks for the reply @benubois. I would, but I emailed a while ago about another of the myriad issues I'm having with it and heard nothing back - not even an acknowledgement - so I don't think I'll bother.

It's a shame, because it's great when it works, but I suppose just with my selection of feeds that's an unfortunately rare occurrence; most things seem to have unrendered math, broken code, a mess of nested tables, or as in this case just be outright missing content.

**Comment by radoslawcz** [comment]
@benubois Thanks for the fix. Images now show correctly :)
