### ISSUE TITLE
Any way for saving searches into new folders?

### ISSUE THREAD

**Issue by bouleusis** [feedbin/support#574]
I have seen how to save the searches in order to star them or to mark read them. But this way only serves to do ONE search. I want to save two different searches. The right way is doing into folders. Any solution?
Thanks

**Comment by benubois** [comment]
Hi @bouleusis,

There's no way to put a saved search in a folder currently.

However you can have one search that searches for multiple terms. For example:

```
"search one" OR "search two"
```
