### ISSUE TITLE
Keyboard shortcuts cheatsheet invisible with theme-night

### ISSUE THREAD

**Issue by rik** [feedbin/support#575]
The text is white on a white background.

The CSS that does this:
```css
body.theme-night {
	color:#FFFFFF;
```

![keyboard-shortcuts](https://cloud.githubusercontent.com/assets/3653/24963922/34db56d2-1fa0-11e7-8211-33a7aab6a55f.png)

**Comment by benubois** [comment]
Thanks for reporting this! Should be fixed now.

**Comment by rik** [comment]
Thanks for the super quick fix.
