### ISSUE TITLE
Payment Issue

### ISSUE THREAD

**Issue by nikihb** [feedbin/support#577]
I'm being charged $2 a month even though I am on the $20 a year plan. Help please....

<img width="1280" alt="screen shot 2017-05-29 at 19 00 09" src="https://cloud.githubusercontent.com/assets/1695442/26558564/adc12e02-44a1-11e7-9e4e-08883a0b85f1.png">

**Comment by benubois** [comment]
Hi, please email support@feedbin.com for any billing issue. This is a public support channel. Thanks!
