### ISSUE TITLE
Petrolicious.com Feed URLs

### ISSUE THREAD

**Issue by tpitale** [feedbin/support#584]
https://gist.github.com/tpitale/c4055e418148f668bbccb3c3685471fc

All the links seem to go to the channel -> link url `https://staging.petrolicious.com` rather than to the links provided in the individual `item`s e.g.,

```
<guid isPermaLink="true">https://petrolicious.com/articles/here-are-seven-of-the-prettiest-cars-to-ever-claim-the-land-speed-record</guid>
```

I don't think the `guid` is _supposed_ to include a link. So yeah … I've told Petrolicious about this. Not sure if there is anything Feedbin needs to do (or even can do).

If I can find out which RSS/Atom parser library you use I'm happy to try debug and PR with them.

**Comment by benubois** [comment]
Hi @tpitale,

Thanks for reporting this! Somehow it never came up before. 

Should be fixed soon.

**Comment by tpitale** [comment]
Thank you!
