### ISSUE TITLE
Feed not updating: http://lwkd.info

### ISSUE THREAD

**Issue by ksuther** [feedbin/support#586]
Feedbin is showing the last update as March 4 even though there have been multiple updates since then. Feed and headers are attached to the issue.

[headers.txt](https://github.com/feedbin/support/files/2091897/headers.txt)
[feed.txt](https://github.com/feedbin/support/files/2091898/feed.txt)

**Comment by benubois** [comment]
Looks like the site is mistakenly using the same `id` for every entry: `<id>http://lwkd.info/2018/update</id>`

The `id` is used to determine uniqueness, so all the entries look identical.

Looks like they're using Jekyll as a generator. I use this for Jekyll RSS templates:

```xml
<id>{{ post.id }}</id>
```

**Comment by ksuther** [comment]
Thank you for checking this!
