### ISSUE TITLE
Posts do not display correctly

### ISSUE THREAD

**Issue by am1t** [feedbin/support#588]
I see the posts from a feed for [blot blog](https://blog.amitgawande.com) do not display correctly. Feedbin reader skips the html and only displays the text (when the feed does have html tags). Other feed readers display the content correctly. Always need to fetch the full content for the reader to display with all the html intact.

[Gist](https://gist.github.com/am1t/a436d6da0f8119a62489ed24b82f601d)

**Comment by benubois** [comment]
Hi @am1t,

There's a couple of issues with the feed that is preventing it from being parsed correctly. Try getting your feed to pass [validation](https://blog.amitgawande.com/feed.rss).

The main thing is that whenever you use html, you must enclose the content in CDATA tags:

Incorrect:

```xml
<description>
    <p>Content</p>
</description>
```


Correct:

```xml
<description>
    <![CDATA[
        <p>Content</p>
    ]]>
</description>
```
