### ISSUE TITLE
Retweets not appearing in feed, but only on a few systems / browsers

### ISSUE THREAD

**Issue by briankendall** [feedbin/support#596]
I'm subscribed to a few twitter feeds on my feedbin account, but on one of my computers (a mac running macOS 10.14.4) both Safari and Firefox will not display any retweets for those feeds. I have confirmed that all of them are set to display retweets. The missing retweets are also counted in the unread items for those feeds.

Strangely, if I open feedbin.com in Chrome on that system, or I use feedbin on any other computer, it does display the retweets. So this issue is only affecting these two browsers on one system!

I tried clearing out all cookies and caches in Safari and it didn't fix the problem. Oddly enough, one (but only one) of the times I did that, it displayed the retweets for about twenty seconds before removing them again. Subsequent times I tried clearing out its cookies and caches the retweets never appeared at all.

I have no idea why this is happening or what connection there is between Safari and Firefox on the one system that exhibits this problem.

**Comment by benubois** [comment]
That is very strange. Do you have any extensions or blockers that could be doing something?

**Comment by briankendall** [comment]
@benubois Not sure why I didn't think to check that! It turns out one of my ublock filters was causing the issue. Thanks.
