### ISSUE TITLE
Feed not updating

### ISSUE THREAD

**Issue by jefflub** [feedbin/support#600]
The feed http://meadowparty.com/blog/feed/ is updating on the site, but not in feedbin.

Current feed: https://gist.github.com/1157c171c719e9d84f4fa1cb01b3b19e

**Comment by benubois** [comment]
Hi @jefflub,

The feed looks good to me. Perhaps you caught it in the 26 minute period between when the latest article was published and when Feedbin picked it up?

**Comment by jefflub** [comment]
Thanks for looking @benubois 

This feed looks fine, but hasn't updated for me in Feedbin since 10/12, despite multiple entries in the feed since then.

**Comment by benubois** [comment]
Ah, I see. I think this might be account specific because it is updating in general.

You might check your [subscription settings](https://feedbin.com/settings/subscriptions) to see if it is muted or if its entries are being marked as read by an [Action](https://feedbin.com/settings/actions).

**Comment by jefflub** [comment]
I don't have any Actions in my account, and the feed is not muted. I did mute and unmute it just to be sure.

**Comment by benubois** [comment]
Ok, last guess. There's an old version of this feed in Feedbin's database `http://meadowparty.com/blog/?feed=rss2`

When Feedbin tries to fetch that one, it gets a weird response instead of a redirect.

You might try subscribing to `http://meadowparty.com/blog/feed/`. If this creates a duplicate for you, then you are subscribed to the old feed and can unsubscribe from it.

```
$ curl -v "http://meadowparty.com/blog/?feed=rss2"
*   Trying 45.60.22.125...
* TCP_NODELAY set
* Connected to meadowparty.com (45.60.22.125) port 80 (#0)
> GET /blog/?feed=rss2 HTTP/1.1
> Host: meadowparty.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html
< Cache-Control: no-cache
< Connection: close
< Content-Length: 855
< X-Iinfo: 14-168083495-0 0NNN RT(1573495659398 0) q(0 -1 -1 -1) r(0 -1) B12(4,315,0) U18
< Set-Cookie: visid_incap_2172316=26pyjcYaSMiI8POARqn2UmujyV0AAAAAQUIPAAAAAACK+FHzSFRBAwZgHWidMV9R; expires=Tue, 10 Nov 2020 09:06:00 GMT; path=/; Domain=.meadowparty.com
< Set-Cookie: incap_ses_1213_2172316=oetzESuoNQSjLigC8HHVEGujyV0AAAAAEjWsCUDo9k6Wi3CEF6wLeQ==; path=/; Domain=.meadowparty.com
< 
* Closing connection 0
<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3"></script></head><body style="margin:0px;height:100%"><iframe id="main-iframe" src="/_Incapsula_Resource?SWUDNSAI=9&xinfo=14-168083495-0%200NNN%20RT%281573495659398%200%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B12%284%2c315%2c0%29%20U18&incident_id=1213000950288467855-692037892821550590&edet=12&cinfo=04000000&rpinfo=0" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 1213000950288467855-692037892821550590</iframe></body></html>
```

**Comment by jefflub** [comment]
That seems to have worked. Thanks!
