### ISSUE TITLE
Doesn't recognize CraigsList RSS Feeds

### ISSUE THREAD

**Issue by yphoenix** [feedbin/support#603]
When I try to add a feed such as:

https://sfbay.craigslist.org/search/sfc/acc?format=rss&is_telecommuting=1

I get an error message that the feed doesn't exist.

Gist: https://gist.github.com/yphoenix/3d2a6e918985574ab6373568ef615971

**Comment by benubois** [comment]
Sorry for the trouble! Unfortunately Craigslist aggressively blocks bots, which Feedbin is.

Craigslist is unwilling or unable to address the issue.

**Comment by yphoenix** [comment]
Thanks for the response. Yeah they do seem to be a law unto themselves and make very arbitrary decisions like this that IMHO work against them. I’ll set up a “tunnel” through one of my own servers to get around this.

**Comment by yphoenix** [comment]
I figure CL assumed that the RSS feed was the easiest way for people to rip off the ads placed there and re-post elsewhere - and they would be right. Looks like they ban almost any IP address not at the end of a residential connection. Oh well.
