### ISSUE TITLE
blog.danieljanus.pl Atom Feed

### ISSUE THREAD

**Issue by pyrmont** [feedbin/support#607]
I can't add the Atom feed at [blog.danieljanus.pl](http://blog.danieljanus.pl) ([feed URL](http://blog.danieljanus.pl/atom.xml)) to Feedbin. When I try, I get an error message saying 'No feed found'. I've copied the feed (as it currently is) together with the headers to [this Gist](https://gist.github.com/pyrmont/eeca4bd867d1bc93647f1fbb49ea7c8b).

For what it's worth, the W3C validator [describes it](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fblog.danieljanus.pl%2Fatom.xml) as being valid.

**Comment by benubois** [comment]
Looks like the feed is using a [custom namespace](https://validator.w3.org/feed/docs/warning/AvoidNamespacePrefix.html), which [Feedbin's parser](https://github.com/feedjira/feedjira) does not support.

```xml
<a:feed xmlns:a="http://www.w3.org/2005/Atom">
```
