### ISSUE TITLE
RSS feed: MacRumors – broken images

### ISSUE THREAD

**Issue by rauschma** [feedbin/support#609]
* Feed URL: http://www.macrumors.com/macrumors.xml
* Gist with files: https://gist.github.com/rauschma/96a99d6b929b25739c0fd006d4ec464a
* Tip: The `curl` options should include `--location` (i.e., `-svL`) so that feeds are also downloaded if there are redirects.

Problem – images are not shown:
![feedbin-macrumors](https://user-images.githubusercontent.com/526114/73382781-73af9280-42c8-11ea-8629-aa3ae633ca8a.jpg)

**Comment by benubois** [comment]
Thanks for reporting this! MacRumors is dynamically serving webp images based on the `Accept` header.

Looks like Feedbin's image proxy CDN was ignoring `Accept` in the cache key so it was sometimes serving a webp image to a browser that didn't support it.

Should be fixed now, though you will probably have to clear your browser cache to see it on articles you have already viewed.

**Comment by rauschma** [comment]
Interesting! Thanks for the fix.

**Comment by rauschma** [comment]
Alas, there are still occasionally images missing (Safari).
<img width="648" alt="feedbin missing images" src="https://user-images.githubusercontent.com/526114/75610462-9de7b080-5b11-11ea-9e9b-8c9f26810261.png">

**Comment by benubois** [comment]
I feel like this was working for a bit after the last change? Am I crazy? 

Anyway, now I've turned off passing `Accept` headers upstream so everyone gets `image/jpeg`.

Again, you'll need to clear your cache to see images on already viewed articles. Surprised Safari caches `Content-Types` it doesn't understand. Or not. I don't know how browsers work.

**Comment by rauschma** [comment]
It looks like this did the trick.

AFAICT, the previous fix worked for some entries, but not for all of them.
