### ISSUE TITLE
"No feed found." Error.

### ISSUE THREAD

**Issue by sjoonk** [feedbin/support#611]
Hi, there.

I have a feed to subscribe: https://villiv.co.kr/feed 

When I add this feed url to Feedbin, "No feed found." error occurred.
This is my gist file: https://gist.github.com/sjoonk/130b0c6c0e526bdea6f223027ac76b04

Can you fix this?

cf. When i add this feed to Feedly, it works.

**Comment by benubois** [comment]
Looks like a server misconfiguration. When I try to validate the feed, an HTML page is returned. This would need to be fixed by the publisher. 

http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fvilliv.co.kr%2Ffeed
