### ISSUE TITLE
Evernote share failing to connect. iPad

### ISSUE THREAD

**Issue by tonydehnke** [feedbin/support#613]
When trying to share a article to Evernote - Feedbin shows a failed to connect error

**Comment by benubois** [comment]
Not seeing any general issues with Evernote.

Try deactivating then activating on https://feedbin.com/settings/sharing to ensure Feedbin still has access.

**Comment by tonydehnke** [comment]
That seems to have worked!  Thanks.  Perhaps the error code could add this detail or link to tips to fix?

**Comment by tonydehnke** [comment]
So tried to do a share to Evernote again this morning and it failed.  Removed the permission and added it again, still failed.

![image](https://user-images.githubusercontent.com/36720180/82134160-e5cbc900-981e-11ea-9336-744d9fb64384.jpeg)

**Comment by benubois** [comment]
Hi @tonydehnke,

Still not seeing any general problems with Evernote, so this is probably account or article specific.

Could you email support@feedbin.com with:

- Your account email address
- The feed url and article you were trying to save to Evernote.

Thanks!

Ben
