### ISSUE TITLE
Old version of Helsingin Sanomat front page feed served

### ISSUE THREAD

**Issue by oniskanen** [feedbin/support#614]
I tried to add the feed at http://www.hs.fi/rss/teasers/etusivu.xml to Feedbin. Adding the feed goes well, but the content is from 2018.

<img width="1400" alt="feedbin-hs" src="https://user-images.githubusercontent.com/2902357/82157517-9b803180-988a-11ea-8e80-877ea87fe473.png">

Here's the gist showing the latest results from the feed:
https://gist.github.com/Klipi/6300eb43e56af3ff70f8736c14c5ec1e

I needed to pass the `-L` flag to `curl` as there was a HTTP redirect configured on the original URL.

**Comment by Klipi** [comment]
Waiting 20 min seems to have refreshed the feed
